services:
  db:
    image: kartoza/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: safe_map_db
      POSTGRES_USER: mika
      POSTGRES_PASSWORD: Tennoudai3326
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./safe_map_db_dump.sql:/docker-entrypoint-initdb.d/safe_map_db_dump.sql

  backend:
    build: ./backend
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    env_file:
      - .env

volumes:
  pg_data:
