version: "3.9"
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: safemap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DB_URL: postgresql://postgres:postgres@db:5432/safemap

volumes:
  pg_data:
